services:
  - type: web
    name: botnews9999-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python botnews.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: EMAIL_SENDER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_RECIPIENT
        sync: false
      - key: VIETCAPITAL_EMAILS
        sync: false
  - type: worker
    name: botnews9999-scheduler
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python scheduler.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: EMAIL_SENDER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_RECIPIENT
        sync: false
      - key: VIETCAPITAL_EMAILS
        sync: false 